### ISSUE TITLE
API keys still on git

### ISSUE THREAD

**Issue by Ronserruya** [Ethan0429/INSTAMEMES#1]
Hey, just wanted to warn you that your API keys are still visible on git, you should change them

https://github.com/Ethan0429/INSTAMEMES/commit/f81d5714abaf8f3cd6f23af07bb662123c1b16a5#diff-ce8c5b1f06d9f34c15d395b471f01bb2

**Comment by Ethan0429** [comment]
Thanks man! I realized it last night and changed them right away :)
